In [19]:
import numpy as np
from collections import Counter, OrderedDict
from pprint import pprint

In [27]:
game = np.zeros((9,9))
game = game.astype(int)
fillspots = [
    (1,2,7),(1,4,2),(1,8,4),
    (2,3,8),
    (3,4,1),(3,5,9),(3,6,5),(3,9,3),
    (4,2,5),(4,4,6),(4,6,7),(4,7,2),(4,9,9),
    (6,1,4),(6,3,7),(6,4,9),(6,6,1),(6,8,3),
    (7,1,2),(7,4,5),(7,5,3),(7,6,6),
    (8,7,9),
    (9,2,8),(9,6,9),(9,8,6)
]
for points in fillspots:
    rowPos, colPos, val = points
    game[rowPos-1, colPos-1] = val
game

array([[0, 7, 0, 2, 0, 0, 0, 4, 0],
       [0, 0, 8, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 9, 5, 0, 0, 3],
       [0, 5, 0, 6, 0, 7, 2, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 7, 9, 0, 1, 0, 3, 0],
       [2, 0, 0, 5, 3, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 9, 0, 0],
       [0, 8, 0, 0, 0, 9, 0, 6, 0]])

In [28]:
def checkIfGameWon(gameArray):
    if 0 in gameArray:
        return False
    else: return True
def checkForDuplicates(array):
    """Utility Function.
    Arguments:
                array: Numpy array
    Returns:
        Boolean. False if there are no duplicate values in the array. True if there are
        """
    flatArray = array.flatten()
    duplicates = [item for item, count in Counter(flatArray).items() if count > 1]
    if 0 in duplicates:
        duplicates.remove(0)
    if len(duplicates) > 0:
        return True
    else: return False 
def flattenRowColumnandCube(position, tempGame):
    """Utility function.
    Arguments:
                position: Tuple pair of integers
    Returns:
                flatRow, flatCol, FlatCube: flat (9,) array
    """
    #Get a row and column array
    gameRow, gameCol = position
    tempGameRow = tempGame[gameRow, :]
    tempGameCol = tempGame[:, gameCol]
    #get the 9 member square location into its own array
    if gameRow >= 0 and gameRow <= 2 and gameCol >= 0 and gameCol <= 2:
        tempGameCube = tempGame[0:3, 0:3]
    elif gameRow >= 0 and gameRow <= 2 and gameCol >= 3 and gameCol <= 5:
        tempGameCube = tempGame[0:3, 3:6]
    elif gameRow >= 0 and gameRow <= 2 and gameCol >= 6 and gameCol <= 9:
        tempGameCube = tempGame[0:3, 6:9]
    elif gameRow >= 3 and gameRow <= 5 and gameCol >= 0 and gameCol <= 2:
        tempGameCube = tempGame[3:6, 0:3]
    elif gameRow >= 3 and gameRow <= 5 and gameCol >= 3 and gameCol <= 5:
        tempGameCube = tempGame[3:6, 3:6]
    elif gameRow >= 3 and gameRow <= 5 and gameCol >= 6 and gameCol <= 9:
        tempGameCube = tempGame[3:6, 6:9]
    elif gameRow >= 6 and gameRow <= 8 and gameCol >= 0 and gameCol <= 2:
        tempGameCube = tempGame[6:9, 0:3]
    elif gameRow >= 6 and gameRow <= 8 and gameCol >= 3 and gameCol <= 5:
        tempGameCube = tempGame[6:9, 3:6]
    elif gameRow >= 6 and gameRow <= 8 and gameCol >= 6 and gameCol <= 9:
        tempGameCube = tempGame[6:9, 6:9]
    return tempGameRow.flatten(), tempGameCol.flatten(), tempGameCube.flatten()
def copyGameandSetNumberForTesting(position, value, tempGame):
    temporaryGame = tempGame.copy()
    gameRow, gameCol = position
    temporaryGame[gameRow, gameCol] = value
    return temporaryGame
def validatenumber(position, value, tempGame):
    """Utility function. 
    Arguments: 
                Position: Tuple pair of integers
                Value: Integer. Tentative value to be played
    Returns:
                validNumber: Boolean. True if value is valid to play in position. False if value is illegal
    """
    tempGameCopytoCheckIfValidNumber = copyGameandSetNumberForTesting(position, value, tempGame)
    flatRow, flatCol, flatCube = flattenRowColumnandCube(position, tempGameCopytoCheckIfValidNumber)
    if not checkForDuplicates(flatRow) and not checkForDuplicates(flatCol) and not checkForDuplicates(flatCube):
        return True
    else: return False
def allPossibleMoves(game):
    possibleMovesDict = OrderedDict()
    #fill possibleMovesDict at position with valid moves
    for rowPosition in range(game.shape[0]):
        for colPosition in range(game.shape[1]):
            if game[rowPosition][colPosition] != 0:
                possibleMovesDict[(rowPosition,colPosition)] = [game[rowPosition][colPosition]]
            else:
                possibleMovesDict[(rowPosition,colPosition)] = []
                for value in range(1,10):
                    if validatenumber((rowPosition, colPosition), value, game):
                        possibleMovesDict[(rowPosition,colPosition)].append(value)
    return possibleMovesDict
def fillGametoTest(game, values):
    tempGame = game.copy()
    for coordinate, value in values:
        if tempGame[coordinate] == 0:
            tempGame[coordinate] = value
    return tempGame
def checkGame(game):
    for rowPosition in range(game.shape[0]):
        for colPosition in range(game.shape[1]):
            if not validatenumber((rowPosition, colPosition), game[rowPosition, colPosition], game):
                return False
    return True
def comboGenerator(combos):
    for combo in combos:
        yield combo

In [29]:
continueLooping = True
filledGame = game.copy()
valueCounter = 0
while continueLooping:
    tempGame = filledGame.copy()
    counter = 0
    possibleMovesDict = allPossibleMoves(tempGame)
    for coordinate in possibleMovesDict.keys():
        if len(possibleMovesDict[coordinate]) == 1 and tempGame[coordinate] == 0:
            tempGame[coordinate] = possibleMovesDict[coordinate][0]
            counter += 1
            valueCounter += 1
    filledGame = tempGame
    if counter == 0:
        continueLooping = False
print("Was able to fill in {} moves".format(str(valueCounter)))
pprint(game)
pprint(filledGame)
game = filledGame

Was able to fill in 1 moves
array([[0, 7, 0, 2, 0, 0, 0, 4, 0],
       [0, 0, 8, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 9, 5, 0, 0, 3],
       [0, 5, 0, 6, 0, 7, 2, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 7, 9, 0, 1, 0, 3, 0],
       [2, 0, 0, 5, 3, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 9, 0, 0],
       [0, 8, 0, 0, 0, 9, 0, 6, 0]])
array([[0, 7, 0, 2, 0, 0, 0, 4, 0],
       [0, 0, 8, 0, 0, 0, 0, 0, 0],
       [6, 0, 0, 1, 9, 5, 0, 0, 3],
       [0, 5, 0, 6, 0, 7, 2, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 7, 9, 0, 1, 0, 3, 0],
       [2, 0, 0, 5, 3, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 9, 0, 0],
       [0, 8, 0, 0, 0, 9, 0, 6, 0]])


In [30]:
#loop through each coordinate key
combos = []
counter = 0
possibleMovesDict = allPossibleMoves(game)
for coordinate in possibleMovesDict.keys():
    counter += 1
    if len(possibleMovesDict[coordinate]) == 1:
        if len(combos) == 0:
            combos.append([(coordinate, possibleMovesDict[coordinate][0])])
        else:
            for index, combo in enumerate(combos):
                combos[index].append((coordinate, possibleMovesDict[coordinate][0]))
    else:
        if len(combos) == 0:
            for value in possibleMovesDict[coordinate]:
                combos.append([(coordinate, value)])
        else:
            #each path in combos needs to be printed x times, x being the length of possible moves
            tempList = []
            for combo in comboGenerator(combos):
                comboGameToCheck = fillGametoTest(game, combo)
                if checkGame(comboGameToCheck):
                    for value in possibleMovesDict[coordinate]:
                        tempList.append(combo + [(coordinate, value)])
            combos = list(tempList)
    print("{}/81 squares solved with a total of {} combinations found".format(len(combos[0]), len(combos)))

1/81 squares solved with a total of 4 combinations found
2/81 squares solved with a total of 4 combinations found
3/81 squares solved with a total of 16 combinations found
4/81 squares solved with a total of 16 combinations found
5/81 squares solved with a total of 24 combinations found
6/81 squares solved with a total of 48 combinations found
7/81 squares solved with a total of 96 combinations found
8/81 squares solved with a total of 96 combinations found
9/81 squares solved with a total of 128 combinations found
10/81 squares solved with a total of 80 combinations found
11/81 squares solved with a total of 200 combinations found
12/81 squares solved with a total of 200 combinations found
13/81 squares solved with a total of 324 combinations found
14/81 squares solved with a total of 588 combinations found
15/81 squares solved with a total of 480 combinations found
16/81 squares solved with a total of 256 combinations found
17/81 squares solved with a total of 320 combinations found


In [31]:
solutions = []
for index, combo in enumerate(combos):
    #print("Checking {} / {} games".format(index+1, len(combos)))
    comboGameToCheck = fillGametoTest(game, combo)
    if checkGame(comboGameToCheck):
        solutions.append(comboGameToCheck)
print("Game won!! Found {} solution(s) out of a total of {} choices".format(len(solutions), len(combos)))
for solution in solutions:
    print(solution)

Game won!! Found 1 solution(s) out of a total of 5 choices
[[3 7 9 2 6 8 5 4 1]
 [5 1 8 4 7 3 6 9 2]
 [6 4 2 1 9 5 7 8 3]
 [8 5 3 6 4 7 2 1 9]
 [9 6 1 3 8 2 4 5 7]
 [4 2 7 9 5 1 8 3 6]
 [2 9 4 5 3 6 1 7 8]
 [7 3 6 8 1 4 9 2 5]
 [1 8 5 7 2 9 3 6 4]]
