In [1]:
import numpy as np
from collections import Counter, OrderedDict
from pprint import pprint

In [11]:
game = np.zeros((9,9))
game = game.astype(int)
fillspots = [
    (1,1,6),(1,2,2),(1,8,5),
    (2,4,2),(2,8,8),
    (3,3,9),(3,5,4),(3,6,7),
    (4,3,1),(4,5,5),(4,7,6),
    (5,1,4),(5,4,1),(5,6,9),(5,9,8),
    (6,3,8),(6,5,6),(6,7,9),
    (7,4,4),(7,5,3),(7,7,2),
    (8,2,4),(8,6,1),
    (9,2,7),(9,8,9),(9,9,1)
]
for points in fillspots:
    rowPos, colPos, val = points
    game[rowPos-1, colPos-1] = val
game

array([[6, 2, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 2, 0, 0, 0, 8, 0],
       [0, 0, 9, 0, 4, 7, 0, 0, 0],
       [0, 0, 1, 0, 5, 0, 6, 0, 0],
       [4, 0, 0, 1, 0, 9, 0, 0, 8],
       [0, 0, 8, 0, 6, 0, 9, 0, 0],
       [0, 0, 0, 4, 3, 0, 2, 0, 0],
       [0, 4, 0, 0, 0, 1, 0, 0, 0],
       [0, 7, 0, 0, 0, 0, 0, 9, 1]])

In [12]:
def checkIfGameWon(gameArray):
    if 0 in gameArray:
        return False
    else: return True
def checkForDuplicates(array):
    """Utility Function.
    Arguments:
                array: Numpy array
    Returns:
        Boolean. False if there are no duplicate values in the array. True if there are
        """
    flatArray = array.flatten()
    duplicates = [item for item, count in Counter(flatArray).items() if count > 1]
    if 0 in duplicates:
        duplicates.remove(0)
    if len(duplicates) > 0:
        return True
    else: return False 
def flattenRowColumnandCube(position, tempGame):
    """Utility function.
    Arguments:
                position: Tuple pair of integers
    Returns:
                flatRow, flatCol, FlatCube: flat (9,) array
    """
    #Get a row and column array
    gameRow, gameCol = position
    tempGameRow = tempGame[gameRow, :]
    tempGameCol = tempGame[:, gameCol]
    #get the 9 member square location into its own array
    if gameRow >= 0 and gameRow <= 2 and gameCol >= 0 and gameCol <= 2:
        tempGameCube = tempGame[0:3, 0:3]
    elif gameRow >= 0 and gameRow <= 2 and gameCol >= 3 and gameCol <= 5:
        tempGameCube = tempGame[0:3, 3:6]
    elif gameRow >= 0 and gameRow <= 2 and gameCol >= 6 and gameCol <= 9:
        tempGameCube = tempGame[0:3, 6:9]
    elif gameRow >= 3 and gameRow <= 5 and gameCol >= 0 and gameCol <= 2:
        tempGameCube = tempGame[3:6, 0:3]
    elif gameRow >= 3 and gameRow <= 5 and gameCol >= 3 and gameCol <= 5:
        tempGameCube = tempGame[3:6, 3:6]
    elif gameRow >= 3 and gameRow <= 5 and gameCol >= 6 and gameCol <= 9:
        tempGameCube = tempGame[3:6, 6:9]
    elif gameRow >= 6 and gameRow <= 8 and gameCol >= 0 and gameCol <= 2:
        tempGameCube = tempGame[6:9, 0:3]
    elif gameRow >= 6 and gameRow <= 8 and gameCol >= 3 and gameCol <= 5:
        tempGameCube = tempGame[6:9, 3:6]
    elif gameRow >= 6 and gameRow <= 8 and gameCol >= 6 and gameCol <= 9:
        tempGameCube = tempGame[6:9, 6:9]
    return tempGameRow.flatten(), tempGameCol.flatten(), tempGameCube.flatten()
def copyGameandSetNumberForTesting(position, value, tempGame):
    temporaryGame = tempGame.copy()
    gameRow, gameCol = position
    temporaryGame[gameRow, gameCol] = value
    return temporaryGame
def validatenumber(position, value, tempGame):
    """Utility function. 
    Arguments: 
                Position: Tuple pair of integers
                Value: Integer. Tentative value to be played
    Returns:
                validNumber: Boolean. True if value is valid to play in position. False if value is illegal
    """
    tempGameCopytoCheckIfValidNumber = copyGameandSetNumberForTesting(position, value, tempGame)
    flatRow, flatCol, flatCube = flattenRowColumnandCube(position, tempGameCopytoCheckIfValidNumber)
    if not checkForDuplicates(flatRow) and not checkForDuplicates(flatCol) and not checkForDuplicates(flatCube):
        return True
    else: return False
def allPossibleMoves(game):
    possibleMovesDict = OrderedDict()
    #fill possibleMovesDict at position with valid moves
    for rowPosition in range(game.shape[0]):
        for colPosition in range(game.shape[1]):
            if game[rowPosition][colPosition] != 0:
                possibleMovesDict[(rowPosition,colPosition)] = [game[rowPosition][colPosition]]
            else:
                possibleMovesDict[(rowPosition,colPosition)] = []
                for value in range(1,10):
                    if validatenumber((rowPosition, colPosition), value, game):
                        possibleMovesDict[(rowPosition,colPosition)].append(value)
    return possibleMovesDict
def fillGametoTest(game, values):
    tempGame = game.copy()
    for coordinate, value in values:
        if tempGame[coordinate] == 0:
            tempGame[coordinate] = value
    return tempGame
def checkGame(game):
    for rowPosition in range(game.shape[0]):
        for colPosition in range(game.shape[1]):
            if not validatenumber((rowPosition, colPosition), game[rowPosition, colPosition], game):
                return False
    return True
def comboGenerator(combos):
    for combo in combos:
        yield combo

In [5]:
continueLooping = True
filledGame = game.copy()
valueCounter = 0
while continueLooping:
    tempGame = filledGame.copy()
    counter = 0
    possibleMovesDict = allPossibleMoves(tempGame)
    for coordinate in possibleMovesDict.keys():
        if len(possibleMovesDict[coordinate]) == 1 and tempGame[coordinate] == 0:
            tempGame[coordinate] = possibleMovesDict[coordinate][0]
            counter += 1
            valueCounter += 1
    filledGame = tempGame
    if counter == 0:
        continueLooping = False
print("Was able to fill in {} moves".format(str(valueCounter)))
pprint(game)
pprint(filledGame)
game = filledGame

Was able to fill in 2 moves
array([[0, 9, 0, 0, 0, 4, 0, 0, 1],
       [4, 0, 3, 1, 0, 0, 0, 0, 0],
       [0, 2, 0, 3, 0, 0, 5, 0, 0],
       [0, 4, 6, 0, 0, 0, 1, 0, 0],
       [9, 1, 0, 0, 0, 0, 0, 7, 5],
       [0, 0, 7, 0, 0, 0, 2, 9, 0],
       [0, 0, 4, 0, 0, 3, 0, 5, 0],
       [0, 0, 0, 0, 0, 2, 9, 0, 3],
       [1, 0, 0, 6, 0, 0, 0, 2, 0]])
array([[0, 9, 0, 0, 0, 4, 0, 0, 1],
       [4, 0, 3, 1, 0, 0, 0, 0, 0],
       [0, 2, 0, 3, 0, 0, 5, 0, 0],
       [0, 4, 6, 0, 0, 0, 1, 3, 8],
       [9, 1, 0, 0, 0, 0, 0, 7, 5],
       [0, 0, 7, 0, 0, 0, 2, 9, 0],
       [0, 0, 4, 0, 0, 3, 0, 5, 0],
       [0, 0, 0, 0, 0, 2, 9, 0, 3],
       [1, 0, 0, 6, 0, 0, 0, 2, 0]])


In [13]:
#loop through each coordinate key
combos = []
counter = 0
possibleMovesDict = allPossibleMoves(game)
for coordinate in possibleMovesDict.keys():
    counter += 1
    if len(possibleMovesDict[coordinate]) == 1:
        if len(combos) == 0:
            combos.append([(coordinate, possibleMovesDict[coordinate][0])])
        else:
            for index, combo in enumerate(combos):
                combos[index].append((coordinate, possibleMovesDict[coordinate][0]))
    else:
        if len(combos) == 0:
            for value in possibleMovesDict[coordinate]:
                combos.append([(coordinate, value)])
        else:
            #each path in combos needs to be printed x times, x being the length of possible moves
            tempList = []
            for combo in comboGenerator(combos):
                comboGameToCheck = fillGametoTest(game, combo)
                if checkGame(comboGameToCheck):
                    for value in possibleMovesDict[coordinate]:
                        tempList.append(combo + [(coordinate, value)])
            combos = list(tempList)
    print(len(combos[0]))
print("Total combinations of moves: {}".format(len(combos)))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
Total combinations of moves: 4


In [18]:
solutions = []
for index, combo in enumerate(combos):
    #print("Checking {} / {} games".format(index+1, len(combos)))
    comboGameToCheck = fillGametoTest(game, combo)
    if checkGame(comboGameToCheck):
        solutions.append(comboGameToCheck)
print("Game won!! Found {} solution(s)".format(len(solutions)))
for solution in solutions:
    print(solution)

Game won!! Found 1 solution(s)
[[6 2 7 9 8 3 1 5 4]
 [5 3 4 2 1 6 7 8 9]
 [1 8 9 5 4 7 3 2 6]
 [3 9 1 8 5 2 6 4 7]
 [4 6 2 1 7 9 5 3 8]
 [7 5 8 3 6 4 9 1 2]
 [9 1 6 4 3 8 2 7 5]
 [2 4 5 7 9 1 8 6 3]
 [8 7 3 6 2 5 4 9 1]]


In [ ]:
from pympler import asizeof
for name, obj in locals().items():
    if name != 'asizeof':
        try:
            print(name,": " ,asizeof.asizeof(obj) / 1024)
        except:
            pass